### ISSUE TITLE
모임 일정

### ISSUE THREAD

**Issue by kimkyeongnam** [study-artificial-intelligence/Predict-Movie-Score#1]
어떻게 할래요 ?-?

스터디 + 플젝 일정 같이 정해야할것 같아요~

**Comment by myujin** [comment]
방학 때 현재는 정해진 일정 없어서 아무 때나 가능합니다. 대신에 7월 마지막 주~8월 첫째 주 약 2주간은 개인일정 때문에 빠질 수도 있을 것 같습니다.

**Comment by kimkyeongnam** [comment]
음 일단 제 일정이..
7월 첫째주까지 수금 아르바이트,
7월 2,3째주에 월화수 고교SW멘토링
매주 화요일에 연구실과 영어회화스터디가 있습니다.
인공지능 스터디도 있는데, 그곳은 아직 일정이 확실하게 잡히지 않아서..

일단 7월 첫째주는 월목토일 이렇게는 확실하게 시간이 되는데
음 이번주는 저기 날 중 하나 잡아서 할래요..?
